env: "dev"

database:
  server: "mcs-db.database.windows.net"
  port: 1433
  user: "CloudSAa614fa41"
  password: "library@872"
  name: "library_db"

http_server:
  address: "localhost:8000"

jwt:
  secret: "vikas"
  expiry: "30m"

azure_blob:
  connection_string: 'DefaultEndpointsProtocol=https;AccountName=mcsvikas;AccountKey=TSuudQhqqopI8XqNoVUbbFTNkTb3HMs4riGRs68TGoF4VkVe+JKsC3G4zDcYtbhKQrtT5aqBXPVN+AStLCbJyw==;EndpointSuffix=core.windows.net'
  container_name: "book-covers"

cors:
  allowed_origin: "http://localhost:5173"